In [ ]:
#TASK:01
import numpy as np
x=np.arange(2,33,2).reshape(4,4)
print(x)

In [5]:
#TASK:02'
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape(5,5)
print(X)
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2!=0]
print(Y)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [11]:
X#TASK:03
import numpy as np
x=np.arange(1,5).reshape(4,1)
z=np.ones((1,4))
y= x* np.ones((1,4))
print(y)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [16]:
#TASK:04

from google.colab  import drive
drive.mount('/NumPy.ipnyb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipnyb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[ 0.58366229  1.16041833  1.43377619 ...  0.64660023 -0.06788665
   0.17899818]
 [ 0.9833369   1.36985033  0.69300251 ...  0.15901078  1.50530185
  -1.64619101]
 [ 1.7160737  -0.57606421 -1.65499174 ... -0.98601061 -1.07549604
   1.01319585]
 ...
 [-0.36745343  0.7679067   0.65530055 ... -1.43821621 -0.32802559
  -0.7461535 ]
 [ 1.66044888 -0.4845244   0.10792395 ...  0.69330691 -1.08716454
   0.00998662]
 [-0.89348565 -0.50879632 -0.30051394 ...  0.41023611  0.65418765
   1.07835693]]
Average of all values in X_norm: 3.4638958368304882e-18
Average of minimum values in each column of X_norm: -1.7223386082748693
Average of maximum values in each column of X_norm: 1.7260545089703023
Random permutation of row indices: [ 18 300 404  38 883 504  26 996 816 643 631  97 104 243  31 426 634  61
 605 545  87 331 147 420 153 362 505 551 728 692 785 198 821 778 835 746
 227 272  54 226 472 429